// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace TipCalc.UITest.Windows.Screens.TipCalcViewUIMapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITest.Input;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WindowsRuntimeControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = Microsoft.VisualStudio.TestTools.UITest.Input.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class TipCalcViewUIMap
    {
        
        #region Properties
        public UITipCalcUIUWPWindow UITipCalcUIUWPWindow
        {
            get
            {
                if ((this.mUITipCalcUIUWPWindow == null))
                {
                    this.mUITipCalcUIUWPWindow = new UITipCalcUIUWPWindow();
                }
                return this.mUITipCalcUIUWPWindow;
            }
        }
        #endregion
        
        #region Fields
        private UITipCalcUIUWPWindow mUITipCalcUIUWPWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UITipCalcUIUWPWindow : XamlWindow
    {
        
        public UITipCalcUIUWPWindow()
        {
            #region Search Criteria
            this.SearchProperties[XamlControl.PropertyNames.Name] = "TipCalc.UI.UWP";
            this.SearchProperties[XamlControl.PropertyNames.ClassName] = "Windows.UI.Core.CoreWindow";
            this.WindowTitles.Add("TipCalc.UI.UWP");
            #endregion
        }
        
        #region Properties
        public XamlText UIItem10Text
        {
            get
            {
                if ((this.mUIItem10Text == null))
                {
                    this.mUIItem10Text = new XamlText(this);
                    #region Search Criteria
                    this.mUIItem10Text.SearchProperties[XamlText.PropertyNames.AutomationId] = "TipAmount_TextBox";
                    this.mUIItem10Text.WindowTitles.Add("TipCalc.UI.UWP");
                    #endregion
                }
                return this.mUIItem10Text;
            }
        }
        
        public XamlEdit UISubTotal_TextBoxEdit
        {
            get
            {
                if ((this.mUISubTotal_TextBoxEdit == null))
                {
                    this.mUISubTotal_TextBoxEdit = new XamlEdit(this);
                    #region Search Criteria
                    this.mUISubTotal_TextBoxEdit.SearchProperties[XamlEdit.PropertyNames.AutomationId] = "SubTotal_TextBox";
                    this.mUISubTotal_TextBoxEdit.WindowTitles.Add("TipCalc.UI.UWP");
                    #endregion
                }
                return this.mUISubTotal_TextBoxEdit;
            }
        }
        #endregion
        
        #region Fields
        private XamlText mUIItem10Text;
        
        private XamlEdit mUISubTotal_TextBoxEdit;
        #endregion
    }
}
